# allows you to actually scroll through terminal
set -g mouse on

# rebind prefix to ctrl-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# rebind window splits to | and - (clever binds right?)
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

set -g history-limit 10000

# larger character limit for left side of status bar (session name)
set -g status-left-length 50
