[window]
opacity = 1.0
padding = { x = 10, y = 10 }
decorations = "Full"

[font]
normal.family = "BlexMono Nerd Font"
size = 15.0

[env]
TERM = "xterm-256color"

# Kanagawa Alacritty Colors
#[colors]
# [colors.primary]
# background = '0x1f1f28'
# foreground = '0xdcd7ba'
#
# [colors.selection]
# background = '0x2d4f67'
# foreground = '0xc8c093'
#
# [[colors.indexed_colors]]
# index = 16
# color = '0xffa066'
#
# [[colors.indexed_colors]]
# index = 18
# color = '0xff5d62'

#TokyoNight Moon Colors
[colors]
  [colors.primary]
  background = '0x222436'
  foreground = '0xc8d3f5'

  [colors.selection]
  background = '0x2f334d'
  foreground = '0xc0caf5'

  [[colors.indexed_colors]]
  index = 16
  color = '0xff9e64'

  [[colors.indexed_colors]]
  index = 17
  color = '0xdb4b4b'

